dataset:
  train_csv: "datasets/UNSW_NB15/UNSW_NB15_training-set.csv"          #modificare con tutti i dataset
  test_csv: "datasets/UNSW_NB15/UNSW_NB15_testing-set.csv"

benchmark:
  mode: "fixed"     # ["fixed", "incremental"] 
  param: 1         #single mode: fixed and param = 1 
  strategy: "MER"         #ICaRL, MER, DER

dataset:
  mode: "CICIDS_2017"   #CICIDS_2017, UNSW_NB15

preprocessing:
  drop_columns: ["id", "label"]
  categorical: ["proto", "service", "state"]
  label_column: "attack_cat"
  clip_percentile: 0.99
  add_features: true
  balance_classes: true

output:
  save_preprocessor: "models/preprocessor.pkl"
  save_label_encoder: "models/label_encoder.pkl"

