dataset:
  mode: "UNSW_NB15"   #CICIDS_2017, UNSW_NB15
  train_csv: "datasets/UNSW_NB15/UNSW_NB15_training-set.csv"          
  test_csv: "datasets/UNSW_NB15/UNSW_NB15_testing-set.csv"

optuna: 
  n_trials: 1    #10-15 for test, 100+ for real results
  #output_path: "optuna_best_params.json" ##### we take that from args
  all: false  #with true optuna iterate for each mode and each parameter, if false optuna take the benchmark settings 
  modes: ["fixed", "incremental"]
  strategies: ["ICaRL", "MER", "DER"]
  params: [1, 2]

benchmark:
  mode: "fixed"     # ["fixed", "incremental"] 
  param: 2         #single mode: fixed and param = 1 
  strategy: "ICaRL"         #ICaRL, MER, DER

preprocessing:
  drop_columns: ["id", "label"]
  categorical: ["proto", "service", "state"]
  label_column: "attack_cat"
  clip_percentile: 0.99
  add_features: true
  balance_classes: true

output:
  save_preprocessor: "preprocessing/UNSW_NB15/preprocessor_UNSW_NB15.pkl"
  save_label_encoder: "preprocessing/UNSW_NB15/label_encoder_UNSW_NB15.pkl"
